version: "3.8"
services:
  postgresdb:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  tomcat:
    build: .
    container_name: tomcat
    restart: always
    ports:
      - "8080:8080"
